Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|
    server.vm.network :private_network, ip: "192.168.56.254"
    server.vm.hostname = "server"
    server.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--name", "server"]
    end
    server.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "provisioning/server.yml"
    end
  end

  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.network :private_network, ip: "192.168.56.200"
    manager.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--name", "manager"]
    end
    manager.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "provisioning/manager.yml"
    end
  end

    (1..2).each do |i|
      config.vm.define "client#{i}" do |client|
        client.vm.hostname = "client#{i}"
        client.vm.network :private_network, ip: "192.168.56.10#{i}"
        client.vm.provider :virtualbox do |v|
            v.customize ["modifyvm", :id, "--name", "client#{i}"]
            v.linked_clone = true
        end
        client.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "provisioning/client.yml"
        end
      end
    end


  config.vm.box = "debian/stretch64"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

end
